# https://travis-ci.org/christoph2/copi
#dist: xenial
language: python
sudo: required
python:
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - 3.8

os:
  - windows

notifications:
  email: false

install:
  - pip install -r requirements.txt
  - travis_retry pip install pylint codeclimate-test-reporter
  - travis_retry pip install pytest-cov coverage coveralls codacy-coverage

script:
#  python -m unittest discover ./objutils/tests/
#   python ./objutils/tools/readelf.py
   coverage run --source=copi setup.py test

after_success:
  - pylint copi
  - coveralls
  - coverage xml && python-codacy-coverage -r coverage.xml
  - codeclimate-test-reporter
  - python setup.py bdist_wheel

deploy:
    provider: releases
    skip_cleanup: true
    api_key: $GH_TOKEN
    on:
        tags: true
    file:
        - "dist/*"
